on mine:
    if line 1 of lore of player's held item contains "Optimized for the":
        if line 2 of lore of player's held item contains "best dirt diggers":
            if event-block is dirt:
                drop 1 dirt at event-location
            if event-block is grass:
                if player's held item is enchanted with  silk touch:
                    drop 1 grass block at event-location
                else:
                    drop 1 dirt at event-location

