on armor equip:
	if line 2 of lore of event-item contains "&bManipulates the tide in your favor":
		apply dolphins grace to the player for 9999 days
		wait 1 tick
		while line 2 of lore of player's boots contains "&bManipulates the tide in your favor":
			wait 5 ticks
		remove dolphins grace from player

on armor unequip:
	if line 2 of lore of event-item contains "&bManipulates the tide in your favor":
		remove dolphins grace from player
